-- init.db


CREATE ROLE ${POSTGRES_USER} WITH LOGIN PASSWORD ${POSTGRES_PASSWORD};
ALTER ROLE ${POSTGRES_USER} CREATEDB CREATEROLE;
CREATE DATABASE my_database WITH OWNER ${POSTGRES_USER};
GRANT ALL PRIVILEGES ON DATABASE my_database TO ${POSTGRES_USER};
